# Generated by Django 4.2.11 on 2024-04-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('population', models.CharField(blank=True, max_length=100, null=True)),
                ('terrains', models.TextField()),
                ('climates', models.TextField()),
            ],
        ),
    ]
